/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    BottomNavigation: typeof import('./src/components/BottomNavigation.vue')['default']
    Comment: typeof import('./src/components/Comment.vue')['default']
    Post: typeof import('./src/components/Post.vue')['default']
    QuillEditor: typeof import('./src/components/QuillEditor.vue')['default']
    Reactions: typeof import('./src/components/Reactions.vue')['default']
    Reply: typeof import('./src/components/Reply.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SocialOauth: typeof import('./src/components/SocialOauth.vue')['default']
  }
}
