/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module "vue" {
  export interface GlobalComponents {
    AuthorLink: typeof import("./src/components/AuthorLink.vue")["default"];
    BottomNavigation: typeof import("./src/components/BottomNavigation.vue")["default"];
    CommentComponent: typeof import("./src/components/CommentComponent.vue")["default"];
    CreatedDate: typeof import("./src/components/CreatedDate.vue")["default"];
    PostComponent: typeof import("./src/components/PostComponent.vue")["default"];
    ReactionsComponent: typeof import("./src/components/ReactionsComponent.vue")["default"];
    ReplyComponent: typeof import("./src/components/ReplyComponent.vue")["default"];
    RouterLink: typeof import("vue-router")["RouterLink"];
    RouterView: typeof import("vue-router")["RouterView"];
    SocialOauth: typeof import("./src/components/SocialOauth.vue")["default"];
  }
}
